const constants = {
	CHANGE_HEADLINE: "CHANGE_HEADLINE",
	CHANGE_STANDFIRST: "CHANGE_STANDFIRST",
	CHANGE_DATA: "CHANGE_DATA",
	SET_CHART_TYPE: "SET_CHART_TYPE",
	CHANGE_SOURCE: "CHANGE_SOURCE",
	CHANGE_FOOTNOTE: "CHANGE_FOOTNOTE",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR"
}

export default constants