const constants = {
	CHANGE_HEADLINE: "CHANGE_HEADLINE",
	CHANGE_STANDFIRST: "CHANGE_STANDFIRST",
	CHANGE_DATA: "CHANGE_DATA",
	SET_CHART_TYPE: "SET_CHART_TYPE",
	CHANGE_SOURCE: "CHANGE_SOURCE",
	CHANGE_FOOTNOTE: "CHANGE_FOOTNOTE",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	CHANGE_MARGINS: "CHANGE_MARGINS",
	CHANGE_SVGDIMENSIONS: "CHANGE_SVGDIMENSIONS",
	CHANGE_MARGIN_TOP: "CHANGE_MARGIN_TOP",
	CHANGE_MARGIN_BOTTOM: "CHANGE_MARGIN_BOTTOM",
	CHANGE_MARGIN_LEFT: "CHANGE_MARGIN_LEFT",
	CHANGE_MARGIN_RIGHT: "CHANGE_MARGIN_RIGHT",
	CHANGE_HEADLINE_HEIGHT: "CHANGE_HEADLINE_HEIGHT",
	CHANGE_STANDFIRST_HEIGHT: "CHANGE_STANDFIRST_HEIGHT"
}

export default constants